default:
  ALLOWED_HOSTS: [ ]
  AWS_ACCESS_KEY_ID: ""
  AWS_S3_AVATARS_LOCATION: ""
  AWS_S3_REGION_NAME: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_STORAGE_BUCKET_NAME: ""
  DATABASE_URL: ""
  DEBUG: false
  PORT: 0
  SECRET_KEY: ""

development:
  AWS_ACCESS_KEY_ID: "AKIAJ5FO7DUGUEWO75RA"
  AWS_S3_AVATARS_LOCATION: "avatars-dev"
  AWS_S3_REGION_NAME: "eu-central-1"
  AWS_STORAGE_BUCKET_NAME: "tms-learn-project"
  DEBUG: true
  PORT: 8000
  SECRET_KEY: "1"

heroku:
  ALLOWED_HOSTS:
    - "tms-learn-project.herokuapp.com"
  AWS_ACCESS_KEY_ID: "AKIAJ5FO7DUGUEWO75RA"
  AWS_S3_AVATARS_LOCATION: "avatars-heroku"
  AWS_S3_REGION_NAME: "eu-central-1"
  AWS_STORAGE_BUCKET_NAME: "tms-learn-project"
  DEBUG: false
